USE [master]
GO

/****** Object:  Database [ipMusic]    Script Date: 2015/10/11 13:05:40 ******/
CREATE DATABASE [ipMusic]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ipMusic', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\ipMusic.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ipMusic_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\ipMusic_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ipMusic] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ipMusic].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ipMusic] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ipMusic] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ipMusic] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ipMusic] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ipMusic] SET ARITHABORT OFF 
GO

ALTER DATABASE [ipMusic] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ipMusic] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ipMusic] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ipMusic] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ipMusic] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ipMusic] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ipMusic] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ipMusic] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ipMusic] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ipMusic] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ipMusic] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ipMusic] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ipMusic] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ipMusic] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ipMusic] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ipMusic] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ipMusic] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ipMusic] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ipMusic] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ipMusic] SET  MULTI_USER 
GO

ALTER DATABASE [ipMusic] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ipMusic] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ipMusic] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ipMusic] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ipMusic] SET  READ_WRITE 
GO

